import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy | OpsKnight',
  description: 'Privacy policy for OpsKnight.',
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-zinc-950 text-white pb-24 pt-32 px-6">
      <div className="max-w-3xl mx-auto prose prose-invert prose-slate">
        <h1 className="text-4xl font-bold tracking-tight mb-8 text-white">Privacy Policy</h1>
        
        <p className="text-slate-300 mb-6">Last updated: August 18, 2026</p>

        <p className="text-slate-300 leading-relaxed mb-6">
          This Privacy Policy describes how your personal information is collected, used, and shared when you visit 
          the OpsKnight website.
        </p>

        <h2 className="text-2xl font-semibold mt-12 mb-4 text-white">Data Sovereignty First</h2>
        <p className="text-slate-300 leading-relaxed mb-6">
          OpsKnight is a self-hosted platform. The incident management software itself runs entirely on your own 
          infrastructure. We do not have access to your incident data, user information, on-call schedules, or 
          any internal metrics generated by your self-hosted instance. Your data stays on your servers.
        </p>

        <h2 className="text-2xl font-semibold mt-12 mb-4 text-white">Website Analytics</h2>
        <p className="text-slate-300 leading-relaxed mb-6">
          For the main public website (this site), we use privacy-respecting analytics (Cloudflare) to understand 
          general traffic patterns. This does not track individual users across the web or collect personally 
          identifiable information.
        </p>

        <h2 className="text-2xl font-semibold mt-12 mb-4 text-white">Contact Us</h2>
        <p className="text-slate-300 leading-relaxed mb-6">
          For more information about our privacy practices, if you have questions, or if you would like to make a 
          complaint, please contact us by email or through our GitHub repository.
        </p>
      </div>
    </main>
  );
}
